jobs:

# jobs for the dv pipeline from CI thru TEST environment


# manifest gen for VISUALIZER
  - name: demo-man
    type: manifest
    steps:
      - IN: demo-img
      - IN: demo-img-opts
      - TASK: managed

#/ manifest gen for VISUALIZER

# TEST deployment for VISUALIZER to Amazon ECS
  - name: demo-deploy-test
    type: deploy
    steps:
      - IN: demo-man
#      - IN: demo-params
      - IN: demo-test-ecs
      - TASK: managed

# / TEST deployment for VISUALIZER to Amazon ECS


# Release
  - name: demo-rel
    type: release
    steps:
      - IN: demo-ver
        switch: off
      - IN: demo-deploy-test
        switch: off
      - IN: demo-trigger
        switch: off
      - TASK: managed
        bump: minor
# / Release

# PRODCUTION deployment for VISUALIZER to Amazon ECS
  - name: demo-deploy-prod
    type: deploy
    steps:
      - IN: demo-rel
        switch: off
      - IN: demo-prod-ecs
      - TASK: managed
# / PRODCUTION deployment for VISUALIZER to Amazon ECS
